package EnlyteProject;

public class MitchellInTheNewsContent {
    //private static final String JDBC_URL = "jdbc:mysql://127.0.0.1:3306/mitchellschema";
   // private static final String JDBC_URL = "jdbc:mysql://127.0.0.1:3306/newenlyteschema";
    private static final String JDBC_URL = "jdbc:mysql://127.0.0.1:3306/liveenlyteschema";
    private static final String USERNAME = "root";
    private static final String PASSWORD = "";

    public static void main(String[] args) throws Exception {
        String schemaName = "liveenlyteschema";
        String fileName = "Enlyte Live In The News Sheet_";
        String sqlQuery = "SELECT "
                + "nfd.nid, "
                + "nfd.vid, "
                + "nfd.uid, "
                + "nfd.status, "
                + "nfd.title, "
                + "nfd.created, "
                + "nfd.changed, "
                + "nfd.promote, "
                + "nfd.sticky, "
                + "nfd.publish_on, "
                + "nfd.unpublish_on, "
                + "n.uuid AS node__uuid, "
                + "pa.alias, "
                + "nfb.body_value, "
                + "nfb.body_summary, "
                + "nfb.body_format, "
                + "nflmc.field_link_to_main_content_uri, "
                + "nflmc.field_link_to_main_content_title, "
                + "nfel.field_external_link_value, "
                + "nfell.field_external_link_label_value, "
                + "nffd.field_form_description_value, "
                + "nffd.field_form_description_format, "
                + "nffn.field_form_newsletter_value, "
                + "nfft.field_form_title_value, "
                + "nffcl.field_full_content_link_value, "
                + "media_hero_image.uuid AS node__field_hero_image, "
                + "media_opengraph.uuid AS node__field_opengraph_image, "
                + "media_twitter.uuid AS node__field_twitter_card_image, "
                + "nflof.field_link_on_form_uri, "
                + "nflof.field_link_on_form_title, "
                + "nfpl.field_pardot_link_uri, "
                + "nfpl.field_pardot_link_title, "
                + "nfrgl.field_registration_link_uri, "
                + "nfrgl.field_registration_link_title, "
                + "nfwr.field_webinar_recording_uri, "
                + "nfwr.field_webinar_recording_title, "
                + "nfws.field_webinar_slides_uri, "
                + "nfws.field_webinar_slides_title, "
                + "GROUP_CONCAT(DISTINCT ttd_markets.uuid ORDER BY nfm.delta SEPARATOR ',') AS field_markets_uuids, "
                //+ "GROUP_CONCAT(DISTINCT ttd_primary_topic.uuid SEPARATOR ',') AS field_primary_topic_uuids, "
                + "GROUP_CONCAT(DISTINCT ttd_topics.uuid ORDER BY nftop.delta SEPARATOR ',') AS field_topics_uuids, "
                + "nfol.field_open_link_value, "
                + "nfc.field_colorized_value, "
                + "nfdf.field_display_form_value, "
                + "nfdioc.field_display_image_on_card_value, "
                + "nfdrt.field_display_read_time_value, "
                + "nfdrc.field_display_related_stories_value, "
                + "nfct.field_card_type_value, "
                + "nfrl.field_recording_link_uri, "
                + "nfrl.field_recording_link_title, "
                + "nfs.field_seo_value, "
                + "nfaddcontent.field_additional_content_uri, "
                + "nfaddcontent.field_additional_content_title, "
                + "fmdoc.uuid AS field_document_uuid, "
                + "nfextimgurl.field_external_image_url_value, "
                + "nflink.field_news_link_uri, "
                + "nflink.field_news_link_title, "
                + "fmfnp.uuid AS field_news_pdf_uuid, "
                + "nfopath.field_old_path_value, "
                + "nfshowsearch.field_show_in_search_value, "
                + "media_video.uuid AS field_video_file_uuid, "
                + "media_oembed.uuid AS field_video_oembed_uuid "
                + "FROM node_field_data AS nfd "
                + "LEFT JOIN node AS n ON n.nid = nfd.nid "
                + "LEFT JOIN path_alias AS pa ON CONCAT('/node/', nfd.nid) = pa.path "
                + "LEFT JOIN node__body AS nfb ON nfb.entity_id = nfd.nid "
                + "LEFT JOIN node__field_link_to_main_content AS nflmc ON nflmc.entity_id = nfd.nid "
                + "LEFT JOIN node__field_external_link AS nfel ON nfel.entity_id = nfd.nid "
                + "LEFT JOIN node__field_external_link_label AS nfell ON nfell.entity_id = nfd.nid "
                + "LEFT JOIN node__field_form_description AS nffd ON nffd.entity_id = nfd.nid "
                + "LEFT JOIN node__field_form_newsletter AS nffn ON nffn.entity_id = nfd.nid "
                + "LEFT JOIN node__field_form_title AS nfft ON nfft.entity_id = nfd.nid "
                + "LEFT JOIN node__field_full_content_link AS nffcl ON nffcl.entity_id = nfd.nid "
                + "LEFT JOIN node__field_hero_image AS nfhi ON nfhi.entity_id = nfd.nid "
                + "LEFT JOIN media__field_media_image AS mfmi_hi ON mfmi_hi.entity_id = nfhi.field_hero_image_target_id "
                + "LEFT JOIN media AS media_hero_image ON media_hero_image.mid = mfmi_hi.entity_id "
                + "LEFT JOIN node__field_opengraph_image AS nfogi ON nfogi.entity_id = nfd.nid "
                + "LEFT JOIN media__field_media_image AS mfmi_ogi ON mfmi_ogi.entity_id = nfogi.field_opengraph_image_target_id "
                + "LEFT JOIN media AS media_opengraph ON media_opengraph.mid = mfmi_ogi.entity_id "
                + "LEFT JOIN node__field_twitter_card_image AS nftci ON nftci.entity_id = nfd.nid "
                + "LEFT JOIN media__field_media_image AS mfmi_tci ON mfmi_tci.entity_id = nftci.field_twitter_card_image_target_id "
                + "LEFT JOIN media AS media_twitter ON media_twitter.mid = mfmi_tci.entity_id "
                + "LEFT JOIN node__field_link_on_form AS nflof ON nflof.entity_id = nfd.nid "
                + "LEFT JOIN node__field_pardot_link AS nfpl ON nfpl.entity_id = nfd.nid "
                + "LEFT JOIN node__field_registration_link AS nfrgl ON nfrgl.entity_id = nfd.nid "
                + "LEFT JOIN node__field_webinar_recording AS nfwr ON nfwr.entity_id = nfd.nid "
                + "LEFT JOIN node__field_webinar_slides AS nfws ON nfws.entity_id = nfd.nid "
                + "LEFT JOIN node__field_markets AS nfm ON nfm.entity_id = nfd.nid "
                + "LEFT JOIN taxonomy_term_data AS ttd_markets ON nfm.field_markets_target_id = ttd_markets.tid "
               // + "LEFT JOIN node__field_primary_topic AS nfpt ON nfpt.entity_id = nfd.nid "
               // + "LEFT JOIN taxonomy_term_data AS ttd_primary_topic ON nfpt.field_primary_topic_target_id = ttd_primary_topic.tid "
                + "LEFT JOIN node__field_topics AS nftop ON nftop.entity_id = nfd.nid "
                + "LEFT JOIN taxonomy_term_data AS ttd_topics ON nftop.field_topics_target_id = ttd_topics.tid "
                + "LEFT JOIN node__field_open_link AS nfol ON nfol.entity_id = nfd.nid "
                + "LEFT JOIN node__field_colorized AS nfc ON nfc.entity_id = nfd.nid "
                + "LEFT JOIN node__field_display_form AS nfdf ON nfdf.entity_id = nfd.nid "
                + "LEFT JOIN node__field_display_image_on_card AS nfdioc ON nfdioc.entity_id = nfd.nid "
                + "LEFT JOIN node__field_display_read_time AS nfdrt ON nfdrt.entity_id = nfd.nid "
                + "LEFT JOIN node__field_display_related_stories AS nfdrc ON nfdrc.entity_id = nfd.nid "
                + "LEFT JOIN node__field_card_type AS nfct ON nfct.entity_id = nfd.nid "
                + "LEFT JOIN node__field_recording_link AS nfrl ON nfrl.entity_id = nfd.nid "
                + "LEFT JOIN node__field_seo AS nfs ON nfs.entity_id = nfd.nid "
                + "LEFT JOIN node__field_additional_content AS nfaddcontent ON nfaddcontent.entity_id = nfd.nid "
                + "LEFT JOIN node__field_document AS nfdc ON nfdc.entity_id = nfd.nid "
                + "LEFT JOIN file_managed AS fmdoc ON fmdoc.fid = nfdc.field_document_target_id "
                + "LEFT JOIN node__field_external_image_url AS nfextimgurl ON nfextimgurl.entity_id = nfd.nid "
                + "LEFT JOIN node__field_news_link AS nflink ON nflink.entity_id = nfd.nid "
                + "LEFT JOIN node__field_news_pdf AS nfpdf ON nfpdf.entity_id = nfd.nid "
                + "LEFT JOIN file_managed AS fmfnp ON fmfnp.fid = nfpdf.field_news_pdf_target_id "
                + "LEFT JOIN node__field_old_path AS nfopath ON nfopath.entity_id = nfd.nid "
                + "LEFT JOIN node__field_show_in_search AS nfshowsearch ON nfshowsearch.entity_id = nfd.nid "
                + "LEFT JOIN node__field_video AS nfv ON nfv.entity_id = nfd.nid "
                + "LEFT JOIN media__field_media_video_file AS mfmv ON mfmv.entity_id = nfv.field_video_target_id "
                + "LEFT JOIN media AS media_video ON media_video.mid = mfmv.entity_id "
                + "LEFT JOIN media__field_media_oembed_video AS mfov ON mfov.entity_id = nfv.field_video_target_id "
                + "LEFT JOIN media AS media_oembed ON media_oembed.mid = mfov.entity_id "
                + "WHERE nfd.type = 'in_the_news' "
                + "GROUP BY nfd.nid;";


        CommonFunctionsMigrationUsingDB.exportQueryResultToExcel(JDBC_URL,USERNAME, PASSWORD, schemaName, sqlQuery, fileName);


    }
}
