package EnlyteProject;

public class NewArticle {
    //private static final String JDBC_URL = "jdbc:mysql://127.0.0.1:3306/mitchellschema";
    private static final String JDBC_URL = "jdbc:mysql://127.0.0.1:3306/newenlyteschema";
    //private static final String JDBC_URL = "jdbc:mysql://127.0.0.1:3306/liveenlyteschema";
    private static final String USERNAME = "root";
    private static final String PASSWORD = "";
    public static void main(String[] args) throws Exception {
        String schemaName = "newenlyteschema";
        String fileName = "New Enlyte Articles2_";
        String sqlQuery = "SELECT "
                + "nfd.nid, "
                + "nfd.vid, "
                + "nfd.uid, "
                + "nfd.status, "
                + "nfd.title, "
                + "nfd.created, "
                + "nfd.changed, "
                + "nfd.promote, "
                + "nfd.sticky, "
                + "nfd.publish_on, "
                + "nfd.unpublish_on, "
                + "n.uuid AS node__uuid, "
                + "pa.alias, "
                + "kv.value AS pathauto_state_value, "
                + "nfb.body_value, "
                + "nfb.body_summary, "
                + "nfb.body_format, "
                + "nfbp.field_brand_path_value, "
                + "nfdl.field_document_link_value, "
                + "nfell.field_external_link_label_value, "
                + "nffd.field_form_description_value, "
                + "nffd.field_form_description_format, "
                + "nffn.field_form_newsletter_value, "
                + "nfft.field_form_title_value, "
                + "nffcl.field_full_content_link_value, "
                + "nfol.field_old_url_value, "
                + "media_hero.uuid AS node__field_hero, "
                + "GROUP_CONCAT(DISTINCT media_hero_image.uuid ORDER BY nfhi.delta SEPARATOR ',') AS node__field_hero_image_uuids, "
                + "media_hero_mobile.uuid AS node__field_hero_mobile, "
                + "media_opengraph.uuid AS node__field_opengraph_image, "
                + "media_twitter.uuid AS node__field_twitter_card_image, "
                + "media_video.uuid AS field_video_file_uuid, "
                + "media_oembed.uuid AS field_video_oembed_uuid, "
                + "nfac.field_additional_content_uri, "
                + "nfac.field_additional_content_title, "
                + "nfr.field_resource_uri, "
                + "nfr.field_resource_title, "
                + "nflof.field_link_on_form_uri, "
                + "nflof.field_link_on_form_title, "
                + "nflmc.field_link_to_main_content_uri, "
                + "nflmc.field_link_to_main_content_title, "
                + "nfo.field_origin_uri, "
                + "nfo.field_origin_title, "
                + "nfpu.field_pdf_url_uri, "
                + "nfpu.field_pdf_url_title, "
                + "GROUP_CONCAT(DISTINCT n_author.uuid ORDER BY nfa.delta SEPARATOR ',') AS field_author_uuids, "
                + "GROUP_CONCAT(DISTINCT ttd_markets.uuid ORDER BY nfm.delta SEPARATOR ',') AS field_markets_uuids, "
                + "ttd_primary_topic.uuid AS field_primary_topic_uuids, "
                + "GROUP_CONCAT(DISTINCT ttd_topics.uuid ORDER BY nftop.delta SEPARATOR ',') AS field_topics_uuids, "
                + "nff.field_feature_value, "
                + "nfc.field_colorized_value, "
                + "nfdf.field_display_form_value, "
                + "nfdioc.field_display_image_on_card_value, "
                + "nfdrt.field_display_read_time_value, "
                + "nfdrc.field_display_related_stories_value, "
                + "nfdtol.field_display_thumbnail_on_listi_value, "
                + "nfel.field_external_link_value, "
                + "nfbrand.field_brand_value, "
                + "nfct.field_card_type_value, "
                + "fmdoc.uuid AS field_document_uuid, "
                + "nfs.field_seo_value "
                + "FROM "
                + "node_field_data AS nfd "
                + "LEFT JOIN "
                + "node AS n ON n.nid = nfd.nid "
                + "LEFT JOIN "
                + "path_alias AS pa ON CONCAT('/node/', nfd.nid) = pa.path "
                + "LEFT JOIN "
                + "key_value AS kv ON kv.name = nfd.nid AND kv.collection = 'pathauto_state.node' "
                + "LEFT JOIN "
                + "node__body AS nfb ON nfb.entity_id = nfd.nid "
                + "LEFT JOIN "
                + "node__field_brand_path AS nfbp ON nfbp.entity_id = nfd.nid "
                + "LEFT JOIN "
                + "node__field_document_link AS nfdl ON nfdl.entity_id = nfd.nid "
                + "LEFT JOIN "
                + "node__field_external_link_label AS nfell ON nfell.entity_id = nfd.nid "
                + "LEFT JOIN "
                + "node__field_form_description AS nffd ON nffd.entity_id = nfd.nid "
                + "LEFT JOIN "
                + "node__field_form_newsletter AS nffn ON nffn.entity_id = nfd.nid "
                + "LEFT JOIN "
                + "node__field_form_title AS nfft ON nfft.entity_id = nfd.nid "
                + "LEFT JOIN "
                + "node__field_full_content_link AS nffcl ON nffcl.entity_id = nfd.nid "
                + "LEFT JOIN "
                + "node__field_old_url AS nfol ON nfol.entity_id = nfd.nid "
                + "LEFT JOIN "
                + "node__field_hero AS nfh ON nfh.entity_id = nfd.nid "
                + "LEFT JOIN "
                + "media__field_media_image AS mfmi_h ON mfmi_h.entity_id = nfh.field_hero_target_id "
                + "LEFT JOIN "
                + "media AS media_hero ON media_hero.mid = mfmi_h.entity_id "
                + "LEFT JOIN "
                + "node__field_hero_image AS nfhi ON nfhi.entity_id = nfd.nid "
                + "LEFT JOIN "
                + "media__field_media_image AS mfmi_hi ON mfmi_hi.entity_id = nfhi.field_hero_image_target_id "
                + "LEFT JOIN "
                + "media AS media_hero_image ON media_hero_image.mid = mfmi_hi.entity_id "
                + "LEFT JOIN "
                + "node__field_hero_mobile AS nfhm ON nfhm.entity_id = nfd.nid "
                + "LEFT JOIN "
                + "media__field_media_image AS mfmi_hm ON mfmi_hm.entity_id = nfhm.field_hero_mobile_target_id "
                + "LEFT JOIN "
                + "media AS media_hero_mobile ON media_hero_mobile.mid = mfmi_hm.entity_id "
                + "LEFT JOIN "
                + "node__field_opengraph_image AS nfogi ON nfogi.entity_id = nfd.nid "
                + "LEFT JOIN "
                + "media__field_media_image AS mfmi_ogi ON mfmi_ogi.entity_id = nfogi.field_opengraph_image_target_id "
                + "LEFT JOIN "
                + "media AS media_opengraph ON media_opengraph.mid = mfmi_ogi.entity_id "
                + "LEFT JOIN "
                + "node__field_twitter_card_image AS nftci ON nftci.entity_id = nfd.nid "
                + "LEFT JOIN "
                + "media__field_media_image AS mfmi_tci ON mfmi_tci.entity_id = nftci.field_twitter_card_image_target_id "
                + "LEFT JOIN "
                + "media AS media_twitter ON media_twitter.mid = mfmi_tci.entity_id "
                + "LEFT JOIN "
                + "node__field_video AS nfv ON nfv.entity_id = nfd.nid "
                + "LEFT JOIN "
                + "media__field_media_video_file AS mfmv ON mfmv.entity_id = nfv.field_video_target_id "
                + "LEFT JOIN "
                + "media AS media_video ON media_video.mid = mfmv.entity_id "
                + "LEFT JOIN "
                + "media__field_media_oembed_video AS mfov ON mfov.entity_id = nfv.field_video_target_id "
                + "LEFT JOIN "
                + "media AS media_oembed ON media_oembed.mid = mfov.entity_id "
                + "LEFT JOIN "
                + "node__field_additional_content AS nfac ON nfac.entity_id = nfd.nid "
                + "LEFT JOIN "
                + "node__field_resource AS nfr ON nfr.entity_id = nfd.nid "
                + "LEFT JOIN "
                + "node__field_link_on_form AS nflof ON nflof.entity_id = nfd.nid "
                + "LEFT JOIN "
                + "node__field_link_to_main_content AS nflmc ON nflmc.entity_id = nfd.nid "
                + "LEFT JOIN "
                + "node__field_origin AS nfo ON nfo.entity_id = nfd.nid "
                + "LEFT JOIN "
                + "node__field_pdf_url AS nfpu ON nfpu.entity_id = nfd.nid "
                + "LEFT JOIN "
                + "node__field_author AS nfa ON nfa.entity_id = nfd.nid "
                + "LEFT JOIN "
                + "node AS n_author ON nfa.field_author_target_id = n_author.nid "
                + "LEFT JOIN "
                + "node__field_markets AS nfm ON nfm.entity_id = nfd.nid "
                + "LEFT JOIN "
                + "taxonomy_term_data AS ttd_markets ON nfm.field_markets_target_id = ttd_markets.tid "
                + "LEFT JOIN "
                + "node__field_primary_topic AS nfpt ON nfpt.entity_id = nfd.nid "
                + "LEFT JOIN "
                + "taxonomy_term_data AS ttd_primary_topic ON nfpt.field_primary_topic_target_id = ttd_primary_topic.tid "
                + "LEFT JOIN "
                + "node__field_topics AS nftop ON nftop.entity_id = nfd.nid "
                + "LEFT JOIN "
                + "taxonomy_term_data AS ttd_topics ON nftop.field_topics_target_id = ttd_topics.tid "
                + "LEFT JOIN "
                + "node__field_feature AS nff ON nff.entity_id = nfd.nid "
                + "LEFT JOIN "
                + "node__field_colorized AS nfc ON nfc.entity_id = nfd.nid "
                + "LEFT JOIN "
                + "node__field_display_form AS nfdf ON nfdf.entity_id = nfd.nid "
                + "LEFT JOIN "
                + "node__field_display_image_on_card AS nfdioc ON nfdioc.entity_id = nfd.nid "
                + "LEFT JOIN "
                + "node__field_display_read_time AS nfdrt ON nfdrt.entity_id = nfd.nid "
                + "LEFT JOIN "
                + "node__field_display_related_stories AS nfdrc ON nfdrc.entity_id = nfd.nid "
                + "LEFT JOIN "
                + "node__field_display_thumbnail_on_listi AS nfdtol ON nfdtol.entity_id = nfd.nid "
                + "LEFT JOIN "
                + "node__field_external_link AS nfel ON nfel.entity_id = nfd.nid "
                + "LEFT JOIN "
                + "node__field_brand AS nfbrand ON nfbrand.entity_id = nfd.nid "
                + "LEFT JOIN "
                + "node__field_card_type AS nfct ON nfct.entity_id = nfd.nid "
                + "LEFT JOIN "
                + "node__field_document AS nfdc ON nfdc.entity_id = nfd.nid "
                + "LEFT JOIN "
                + "file_managed AS fmdoc ON fmdoc.fid = nfdc.field_document_target_id "
                + "LEFT JOIN "
                + "node__field_seo AS nfs ON nfs.entity_id = nfd.nid "
                + "WHERE "
                + "nfd.type = 'article' "
                + "GROUP BY "
                + "nfd.nid "
                //+ "HAVING "
                //+ "nfd.nid NOT IN ( "
                //+ "    SELECT nfd_sub.nid "
                //+ "    FROM node_field_data AS nfd_sub "
                //+ "    LEFT JOIN node__field_markets AS nfm_sub ON nfm_sub.entity_id = nfd_sub.nid "
                //+ "    LEFT JOIN node__field_topics AS nftop_sub ON nftop_sub.entity_id = nfd_sub.nid "
                //+ "    WHERE nfd_sub.type = 'article' "
                //+ "      AND (nfm_sub.field_markets_target_id IN (2231, 2246) "
                //+ "           OR nftop_sub.field_topics_target_id IN (2231, 2246)) "
                + ";";


        CommonFunctionsMigrationUsingDB.exportQueryResultToExcel(JDBC_URL,USERNAME, PASSWORD, schemaName, sqlQuery, fileName);

    }
}
